---
db:
  host: localhost
  port: 3306
  user: meetrics
  password: password
  database: meetrics
  rootUser: root
  rootPassword: password
  rootDatabase: mysql

google:
  subject: admin@gmail.com
  domain: yourdomain.com
